# Generated by Django 6.0.3 on 2026-06-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_product_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='UNIX Store', max_length=255)),
                ('email', models.EmailField(blank=True, default='admin@unix.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('shipping_info', models.TextField(blank=True, default='Free shipping on domestic orders over $50.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
